### ISSUE TITLE
Allow promphp/prometheus_client_php library greater than 2.4.0 

### ISSUE THREAD

**Issue by pronata** [tasko-products/symfony-prometheus-exporter#12]
The library is fixed to promphp/prometheus_client_php 2.4.0 and not allowed to be installed with greater version

**Comment by lrotermund** [comment]
Hi @pronata, thanks for the tip. We are currently not using the bundle as we have other internal priorities at the moment, which will of course change again. I am sorry that you are currently faced with an outdated composer.json.

Please feel free to create a pull request and our team will merge it as soon as possible.
